# Generated by Django 5.0.7 on 2024-08-24 18:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile', models.ImageField(upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SellerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('REFUSED', 'Refused')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_message', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PROBLEMATIC', 'Problematic')], default='PENDING', max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='paintings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('show', models.BooleanField(default=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('fav', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.painting')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='paintings',
            field=models.ManyToManyField(through='core.OrderItem', to='core.painting'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocode'),
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(through='core.PromoCodeUsage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=99)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.painting')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home_image_section_1', models.ImageField(upload_to='settings/home_image_section')),
                ('become_seller_video', models.FileField(upload_to='settings/become_seller_video')),
                ('home_story_1_image', models.ImageField(upload_to='settings/home_story_1_image')),
                ('home_story_1_title', models.CharField(max_length=255)),
                ('home_story_2_image', models.ImageField(upload_to='settings/home_story_2_image')),
                ('home_story_2_title', models.CharField(max_length=255)),
                ('home_story_3_image', models.ImageField(upload_to='settings/home_story_3_image')),
                ('home_story_3_title', models.CharField(max_length=255)),
                ('home_story_4_image', models.ImageField(upload_to='settings/home_story_4__image')),
                ('home_story_4_title', models.CharField(max_length=255)),
                ('home_story_5_image', models.ImageField(upload_to='settings/home_story_5_image')),
                ('home_story_5_title', models.CharField(max_length=255)),
                ('core_value_1_title', models.CharField(max_length=255)),
                ('core_value_1_title_description', models.TextField()),
                ('core_value_1_image', models.ImageField(upload_to='settings/core_value_1_image')),
                ('core_value_2_title', models.CharField(max_length=255)),
                ('core_value_2_title_description', models.TextField()),
                ('core_value_2_image', models.ImageField(upload_to='settings/core_value_2_image')),
                ('core_value_3_title', models.CharField(max_length=255)),
                ('core_value_3_title_description', models.TextField()),
                ('core_value_4_image', models.ImageField(upload_to='settings/core_value_3_image')),
                ('hero_about_us_image', models.ImageField(upload_to='settings/hero_about_us_image')),
                ('hero_about_us_description', models.CharField(max_length=100)),
                ('about_image_1', models.ImageField(upload_to='settings/about_image_1')),
                ('about_image_2', models.ImageField(upload_to='settings/about_image_2')),
                ('about_image_3', models.ImageField(upload_to='settings/about_image_3')),
                ('about_story', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
                ('open_hours', models.TextField()),
                ('preview_image', models.ImageField(upload_to='settings/preview_image')),
                ('hero_contact_image', models.ImageField(upload_to='settings/hero_contact_image')),
                ('contact_description', models.TextField()),
                ('show', models.BooleanField()),
                ('home_artist_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_artist_1', to='core.artist')),
                ('home_artist_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_artist_2', to='core.artist')),
                ('home_artist_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_artist_3', to='core.artist')),
                ('home_painting_hero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_1', to='core.painting')),
                ('home_painting_hero_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_2', to='core.painting')),
                ('home_painting_hero_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_3', to='core.painting')),
                ('home_painting_list_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_4', to='core.painting')),
                ('home_painting_list_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_5', to='core.painting')),
                ('home_painting_list_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_6', to='core.painting')),
                ('team', models.ManyToManyField(related_name='team', to='core.artist')),
                ('testimony_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemony_1', to='core.testemonial')),
                ('testimony_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemony_2', to='core.testemonial')),
                ('testimony_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemony_3', to='core.testemonial')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy_paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('Settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setting')),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions_paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('Settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setting')),
            ],
        ),
    ]
