# Generated by Django 5.0.7 on 2024-09-02 17:50

import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_promocode_users_delete_promocodeusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', imagekit.models.fields.ProcessedImageField(upload_to='paintings/')),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='img',
            field=models.OneToOneField(null=True,blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.image'),
            preserve_default=False,
        ),
    ]
