# Generated by Django 5.0.7 on 2024-08-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_default_alter_painting_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testemonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PROBLEMATIC', 'Problematic')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home_image_section_1', models.ImageField(upload_to='settings/home_image_section')),
                ('become_seller_video', models.FileField(upload_to='settings/become_seller_video')),
                ('home_story_1_image', models.ImageField(upload_to='settings/home_story_1_image')),
                ('home_story_1_title', models.CharField(max_length=255)),
                ('home_story_2_image', models.ImageField(upload_to='settings/home_story_2_image')),
                ('home_story_2_title', models.CharField(max_length=255)),
                ('home_story_3_image', models.ImageField(upload_to='settings/home_story_3_image')),
                ('home_story_3_title', models.CharField(max_length=255)),
                ('home_story_4_image', models.ImageField(upload_to='settings/home_story_4__image')),
                ('home_story_4_title', models.CharField(max_length=255)),
                ('home_story_5_image', models.ImageField(upload_to='settings/home_story_5_image')),
                ('home_story_5_title', models.CharField(max_length=255)),
                ('core_value_1_title', models.CharField(max_length=255)),
                ('core_value_1_title_description', models.TextField()),
                ('core_value_1_image', models.ImageField(upload_to='settings/core_value_1_image')),
                ('core_value_2_title', models.CharField(max_length=255)),
                ('core_value_2_title_description', models.TextField()),
                ('core_value_2_image', models.ImageField(upload_to='settings/core_value_2_image')),
                ('core_value_3_title', models.CharField(max_length=255)),
                ('core_value_3_title_description', models.TextField()),
                ('core_value_4_image', models.ImageField(upload_to='settings/core_value_3_image')),
                ('hero_about_us_image', models.ImageField(upload_to='settings/hero_about_us_image')),
                ('hero_about_us_description', models.CharField(max_length=100)),
                ('about_image_1', models.ImageField(upload_to='settings/about_image_1')),
                ('about_image_2', models.ImageField(upload_to='settings/about_image_2')),
                ('about_image_3', models.ImageField(upload_to='settings/about_image_3')),
                ('about_story', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('pinterest', models.URLField(blank=True, null=True)),
                ('open_hours', models.TextField()),
                ('preview_image', models.ImageField(upload_to='settings/preview_image')),
                ('hero_contact_image', models.ImageField(upload_to='settings/hero_contact_image')),
                ('contact_description', models.TextField()),
                ('show', models.BooleanField()),
                ('home_artist_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_artist_1', to='core.artist')),
                ('home_artist_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_artist_2', to='core.artist')),
                ('home_artist_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_artist_3', to='core.artist')),
                ('home_painting_hero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_1', to='core.painting')),
                ('home_painting_hero_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_2', to='core.painting')),
                ('home_painting_hero_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_3', to='core.painting')),
                ('home_painting_list_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_4', to='core.painting')),
                ('home_painting_list_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_5', to='core.painting')),
                ('home_painting_list_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_painting_6', to='core.painting')),
                ('team', models.ManyToManyField(related_name='team', to='core.artist')),
                ('teestemony_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemony_1', to='core.testemonial')),
                ('testemonny_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemony_2', to='core.testemonial')),
                ('testemonny_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testemony_3', to='core.testemonial')),
            ],
        ),
    ]
