# Generated by Django 5.0.7 on 2024-09-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_image_painting_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='painting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='painting', to='core.painting'),
        ),
    ]
