# Generated by Django 5.0.7 on 2024-09-03 03:12

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_painting_img_image_painting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_image_1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/about_image_1'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_image_2',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/about_image_2'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_image_3',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/about_image_3'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='core_value_1_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/core_value_1_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='core_value_2_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/core_value_2_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='core_value_4_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/core_value_3_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='hero_about_us_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/hero_about_us_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='hero_contact_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/hero_contact_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_image_section_1',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/home_image_section_1'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_story_1_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/home_story_1_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_story_2_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/home_story_2_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_story_3_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/home_story_3_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_story_4_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/home_story_4_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='home_story_5_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/home_story_5_image'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='preview_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='settings/preview_image'),
        ),
    ]
