# Generated by Django 5.0.7 on 2024-08-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactrequest_faq_testemonial_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='teestemony_1',
            new_name='testemony_1',
        ),
    ]
