# Generated by Django 5.0.7 on 2024-09-03 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_artist_profile_alter_setting_about_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image',
        ),
    ]
