# Generated by Django 5.0.7 on 2024-08-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_teestemony_1_setting_testemony_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='testemonny_2',
            new_name='testemony_2',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='testemonny_3',
            new_name='testemony_3',
        ),
    ]
