# Generated by Django 5.0.7 on 2024-08-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_testemonny_2_setting_testemony_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='testemony_1',
            new_name='testimony_1',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='testemony_2',
            new_name='testimony_2',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='testemony_3',
            new_name='testimony_3',
        ),
    ]
